services:
  postgres:
    container_name: postgresdb
    image: postgres:12
    restart: unless-stopped
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - it-network  

volumes:
  pgdb_data:   

networks:
  it-network:
    driver: bridge
